# Generated by Django 5.2.17 on 2026-10-10 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_historical_candidate_details(apps, schema_editor):
    Eligibility = apps.get_model('examinations', 'ExamEligibility')
    Attempt = apps.get_model('examinations', 'ExamAttempt')

    for grant in Eligibility.objects.select_related('student').iterator():
        if grant.student_id:
            grant.candidate_name = f"{grant.student.first_name} {grant.student.last_name}".strip()
            grant.candidate_email = grant.student.email
            normalized_name = " ".join(grant.candidate_name.split()).casefold()
            # Do not make a historic duplicate name unique automatically.
            # Those candidates retain their individual legacy access codes.
            if normalized_name and not Eligibility.objects.filter(exam_id=grant.exam_id, candidate_name_normalized=normalized_name).exists():
                grant.candidate_name_normalized = normalized_name
            grant.save(update_fields=['candidate_name', 'candidate_name_normalized', 'candidate_email'])

    for attempt in Attempt.objects.select_related('student').iterator():
        if not attempt.student_id:
            continue
        grant = Eligibility.objects.filter(exam_id=attempt.exam_id, student_id=attempt.student_id).first()
        if grant:
            attempt.eligibility_id = grant.pk
            attempt.candidate_name = grant.candidate_name
            attempt.candidate_email = grant.candidate_email
            attempt.save(update_fields=['eligibility', 'candidate_name', 'candidate_email'])


def reverse_copy_historical_candidate_details(apps, schema_editor):
    # The added values are denormalized historical snapshots; no reversal is needed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_candidate_access_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cohort_code_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='exam',
            name='cohort_code_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='candidate_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='eligibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='examinations.exameligibility'),
        ),
        migrations.AddField(
            model_name='exameligibility',
            name='candidate_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='exameligibility',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='exameligibility',
            name='candidate_name_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exameligibility',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_historical_candidate_details, reverse_copy_historical_candidate_details),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS'), ('eligibility__isnull', False)), fields=('eligibility', 'exam'), name='exam_cohort_one_active_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('eligibility__isnull', False)), fields=('eligibility', 'exam', 'attempt_number'), name='exam_cohort_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='exameligibility',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_name_normalized', ''), _negated=True), fields=('exam', 'candidate_name_normalized'), name='exam_cohort_candidate_name'),
        ),
    ]
