"use client";

import { useState } from "react";
import { CmsPageDraft } from "@/lib/api/cms";
import { Area, buttonClass, Field, inputClass, RichText } from "./Fields";
import { MediaPicker } from "./MediaPicker";
import { Icon } from "@/components/ui/Icon";

export const sectionNames: Record<string, string> = { hero: "Hero", rich_text: "Text", image_with_copy: "Image + Text", feature_list: "Features", stat_grid: "Statistics", cta_banner: "Call to action", article_feed: "News", event_feed: "Events", quote: "Testimonial", gallery: "Gallery", faq: "FAQ", image: "Image", card_grid: "Cards", document_list: "Documents", seminar_list: "Monthly seminars", video_list: "Seminar recordings", training_countdown: "Next training countdown", callout: "Highlight", member_directory: "Member directory", contact_details: "Contact details", partner_logos: "Partner logos", profile_gallery: "Profile photos" };
export type Section = CmsPageDraft["sections"][number];
export function PageCopyFields({ data, onChange, canUpload }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void; canUpload: boolean }) {
  const fields = Array.isArray(data.fields) ? data.fields as Array<{ key: string; label: string; value: string; kind?: string; media_id?: string | null }> : [];
  const update = (index: number, value: string, media_id?: string | null, kind?: string) => onChange({ ...data, fields: fields.map((field, i) => i === index ? { ...field, value, ...(media_id !== undefined ? { media_id } : {}), ...(kind ? { kind } : {}) } : field) });
  const groups: Array<{ title: string; entries: Array<{ field: typeof fields[number]; index: number }> }> = [];
  fields.forEach((field, index) => {
    if (!groups.length || field.label === "Heading" || groups[groups.length - 1].entries.length >= 8) groups.push({ title: field.label === "Heading" ? field.value : "Page text " + (groups.length + 1), entries: [] });
    groups[groups.length - 1].entries.push({ field, index });
  });
  return <div className="space-y-3">{groups.map((group, index) => <details key={index} className="rounded-xl border bg-white"><summary className="cursor-pointer px-5 py-4 font-semibold">{group.title}</summary><div className="space-y-4 border-t p-5">{group.entries.map(({ field, index }) => {
    const isDocument = field.kind === "document" || (field.kind === "link" && /\.pdf(?:$|[?#])/i.test(field.value));
    return field.kind === "image" ? <MediaPicker key={field.key} label={field.label} fallback={field.value} value={field.media_id} canUpload={canUpload} onChange={(id, url) => update(index, url, id)} /> : isDocument ? <MediaPicker key={field.key} label="Approved register PDF" fallback={field.value} value={field.media_id} mediaKind="document" canUpload={canUpload} onChange={(id, url) => update(index, url, id, "document")} /> : field.label === "Text" ? <Area key={field.key} label="Text" value={field.value} onChange={(value) => update(index, value)} /> : <Field key={field.key} label={field.label} value={field.value} onChange={(value) => update(index, value)} />;
  })}</div></details>)}</div>;
}
export const text = (data: Record<string, unknown>, ...keys: string[]) => { for (const key of keys) if (typeof data[key] === "string") return data[key] as string; return ""; };
export function Sections({ sections, onChange, canUpload, sectionTypes = Object.keys(sectionNames), allowAdd = true, addLabel = "+ Add Section", removeLabel = "Remove section" }: { sections: Section[]; onChange: (sections: Section[]) => void; canUpload: boolean; sectionTypes?: string[]; allowAdd?: boolean; addLabel?: string; removeLabel?: string }) {
  const [choice, setChoice] = useState(sectionTypes[0] || "rich_text");
  const update = (index: number, patch: Partial<Section>) => onChange(sections.map((item, i) => i === index ? { ...item, ...patch } : item));
  const move = (index: number, step: number) => { const copy = [...sections]; [copy[index], copy[index + step]] = [copy[index + step], copy[index]]; onChange(copy); };
  return <div className="space-y-3">{sections.map((section, index) => <details key={index} className="rounded-xl border border-[var(--color-line)] bg-white">
    <summary className="cursor-pointer px-5 py-4 font-semibold">{Array.isArray(section.data.legacy_blocks) ? "Page buttons" : text(section.data, "heading", "title", "label") || sectionNames[section.section_type] || "Text"}{!section.is_enabled && <span className="ml-3 text-xs font-normal text-[var(--color-slate)]">Hidden</span>}</summary>
    <div className="space-y-5 border-t border-[var(--color-line)] p-5">
      <div className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-[var(--color-slate)]">{sectionNames[section.section_type] || "Text"}</span><div className="flex gap-2"><button type="button" className={buttonClass} disabled={index === 0} onClick={() => move(index, -1)} aria-label="Move section up"><Icon name="arrow-up" className="h-4 w-4" /></button><button type="button" className={buttonClass} disabled={index === sections.length - 1} onClick={() => move(index, 1)} aria-label="Move section down"><Icon name="arrow-down" className="h-4 w-4" /></button></div></div>
      <SectionFields section={section} onChange={(data) => update(index, { data })} onImage={(id, url) => update(index, { primary_media: id, data: { ...section.data, image_url: url } })} canUpload={canUpload} />
      <div className="flex items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={section.is_enabled} onChange={(e) => update(index, { is_enabled: e.target.checked })} />Show section</label><button type="button" className="text-sm font-semibold text-red-700 underline" onClick={() => { if (window.confirm(`${removeLabel}? Save Changes to apply its removal.`)) onChange(sections.filter((_, i) => i !== index)); }}>{removeLabel}</button></div>
    </div>
  </details>)}
    {allowAdd && <div className="flex flex-wrap items-end gap-3 rounded-xl border border-dashed border-[var(--color-line)] p-5">{sectionTypes.length > 1 && <label className="text-sm font-semibold">Choose Section<select value={choice} className={inputClass} onChange={(e) => setChoice(e.target.value)}>{sectionTypes.map((value) => <option key={value} value={value}>{sectionNames[value] || value}</option>)}</select></label>}<button type="button" className={buttonClass} onClick={() => onChange([...sections, { slot: "main", section_type: choice, position: sections.length, is_enabled: true, data: choice === "training_countdown" ? { home_section: "next_training" } : {}, primary_media: null }])}>{addLabel}</button></div>}
  </div>;
}
function SectionFields({ section, onChange, onImage, canUpload }: { section: Section; onChange: (data: Record<string, unknown>) => void; onImage: (id: string | null, url: string) => void; canUpload: boolean }) {
  const data = section.data;
  const set = (key: string, value: unknown) => onChange({ ...data, [key]: value });
  const items = Array.isArray(data.items) ? data.items.filter((item): item is Record<string, unknown> => !!item && typeof item === "object") : [];
  if (Array.isArray(data.legacy_blocks)) {
    const blocks = data.legacy_blocks as Array<Record<string, unknown>>;
    return <>{blocks.map((block, index) => <div key={index} className="grid gap-4 sm:grid-cols-2"><Field label="Button text" value={text(block, "label")} onChange={(label) => set("legacy_blocks", blocks.map((b, i) => i === index ? { ...b, label } : b))} /><Field label="Button link" value={text(block, "href")} onChange={(href) => set("legacy_blocks", blocks.map((b, i) => i === index ? { ...b, href } : b))} /></div>)}{!blocks.length && <p className="text-sm text-[var(--color-slate)]">This page has no additional buttons.</p>}</>;
  }
  if (section.section_type === "profile_gallery") return <ProfileFields items={items} onChange={(items) => set("items", items)} canUpload={canUpload} />;
  if (section.section_type === "exam_assessment") return <ExamAssessmentFields data={data} onChange={onChange} />;
  if (section.section_type === "document_list") return <DocumentFields items={items} onChange={(items) => set("items", items)} canUpload={canUpload} />;
  if (section.section_type === "gallery") return <GalleryFields data={data} onChange={onChange} canUpload={canUpload} />;
  if (section.section_type === "seminar_list") return <SeminarFields items={items} onChange={(items) => set("items", items)} canUpload={canUpload} />;
  if (section.section_type === "video_list") return <VideoFields items={items} onChange={(items) => set("items", items)} />;
  if (section.section_type === "training_countdown") return <TrainingCountdownFields data={data} onChange={onChange} />;
  if (data.home_section === "training") return <HomeEventsFields data={data} onChange={onChange} />;
  if (data.home_section === "partners") return <HomePartnersFields data={data} onChange={onChange} />;
  const headingKey = ["heading", "title", "label"].find((key) => key in data) || "heading";
  const copyKey = ["copy", "text", "description", "summary"].find((key) => key in data) || "copy";
  const listTypes = ["feature_list", "stat_grid", "card_grid", "faq", "document_list", ...(data.home_section === "hero" ? ["hero"] : [])];
  return <>
    {data.home_section !== "hero" && <><Field label="Heading" value={text(data, headingKey)} onChange={(v) => set(headingKey, v)} />
    {data.home_section ? <><Field label="Short introduction" value={text(data, "eyebrow")} onChange={(v) => set("eyebrow", v)} /><Area label="Description" value={text(data, "description")} onChange={(v) => set("description", v)} />{data.home_section === "introduction" && <RichText label="Content" value={text(data, "copy")} onChange={(v) => set("copy", v)} />}</> : <RichText label="Content" value={text(data, copyKey)} onChange={(v) => set(copyKey, v)} />}</>}
    {!data.home_section && ["hero", "image", "image_with_copy", "quote"].includes(section.section_type) && <MediaPicker value={section.primary_media} fallback={text(data, "image_url")} onChange={onImage} canUpload={canUpload} />}
    {(data.home_section ? ["introduction", "membership", "knowledge", "news", "partners"].includes(String(data.home_section)) : ["hero", "cta_banner", "callout", "image_with_copy"].includes(section.section_type)) && <div className="grid gap-4 sm:grid-cols-2"><Field label="Button text" value={text(data, "button_label")} onChange={(v) => set("button_label", v)} /><Field label="Button link" value={text(data, "button_href")} onChange={(v) => set("button_href", v)} /></div>}
    {section.section_type === "quote" && <Field label="Name and role" value={text(data, "attribution")} onChange={(v) => set("attribution", v)} />}
    {data.home_section === "partners" || section.section_type === "partner_logos" ? <PartnerFields items={items} onChange={(items) => set("items", items)} canUpload={canUpload} categorize={section.section_type === "partner_logos"} /> : listTypes.includes(section.section_type) && <div className="space-y-4">{items.map((item, index) => { const change = (patch: Record<string, unknown>) => set("items", items.map((entry, i) => i === index ? { ...entry, ...patch } : entry)); return <div key={index} className="space-y-3 rounded-lg bg-[var(--color-paper)] p-4">
      <Field label={section.section_type === "faq" ? "Question" : section.section_type === "stat_grid" ? "Value" : "Title"} value={text(item, "title")} onChange={(v) => change({ title: v })} />
      <Area label={section.section_type === "faq" ? "Answer" : "Description"} value={text(item, "description")} onChange={(v) => change({ description: v })} />
      {!!data.home_section && data.home_section !== "hero" && <><Field label="Additional label" value={text((item.metadata || {}) as Record<string, unknown>, "display_meta")} onChange={(value) => change({ metadata: { ...(item.metadata as Record<string, unknown> || {}), display_meta: value } })} />{data.home_section === "training" && <Field label="Event details" value={text((item.metadata || {}) as Record<string, unknown>, "detail")} onChange={(value) => change({ metadata: { ...(item.metadata as Record<string, unknown> || {}), detail: value } })} />}</>}
      {["card_grid", "document_list", "feature_list"].includes(section.section_type) && <Field label="Link" value={text(item, "href")} onChange={(v) => change({ href: v })} />}
      {["gallery", "card_grid", "hero"].includes(section.section_type) && <MediaPicker value={text(item, "media_id")} fallback={text(item, "image_url")} canUpload={canUpload} onChange={(id, url) => change({ media_id: id, image_url: url })} />}
      {data.home_section === "hero" && <div className="grid gap-3 sm:grid-cols-2">{[["eyebrow", "Short introduction"], ["primary_label", "Button text"], ["primary_href", "Button link"], ["secondary_label", "Second button text"], ["secondary_href", "Second button link"], ["feature", "Featured text"], ["alt_text", "Image description"]].map(([key, label]) => <Field key={key} label={label} value={text((item.metadata || {}) as Record<string, unknown>, key)} onChange={(value) => change({ metadata: { ...(item.metadata as Record<string, unknown> || {}), [key]: value } })} />)}</div>}
      <button type="button" className={buttonClass} onClick={() => set("items", items.filter((_, i) => i !== index))}>Remove item</button>
    </div>; })}<button type="button" className={buttonClass} onClick={() => set("items", [...items, { title: "", description: "" }])}>+ Add item</button></div>}
    {["article_feed", "event_feed"].includes(section.section_type) && <p className="text-sm text-[var(--color-slate)]">Published {section.section_type === "article_feed" ? "news" : "events"} appear here automatically.</p>}
  </>;
}
function HomeEventsFields({ data, onChange }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void }) {
  const set = (key: string, value: string) => onChange({ ...data, [key]: value });
  return <div className="space-y-4"><p className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)] p-4 text-sm text-[var(--color-slate)]">Event cards are managed on the main Events page. The homepage automatically displays the first three published events from that page.</p><Field label="Heading" value={text(data, "heading")} onChange={(heading) => set("heading", heading)} /><Field label="Short introduction" value={text(data, "eyebrow")} onChange={(eyebrow) => set("eyebrow", eyebrow)} /><Area label="Description" value={text(data, "description")} onChange={(description) => set("description", description)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Button text" value={text(data, "button_label")} onChange={(button_label) => set("button_label", button_label)} /><Field label="Button link" value={text(data, "button_href")} onChange={(button_href) => set("button_href", button_href)} /></div></div>;
}

function HomePartnersFields({ data, onChange }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void }) {
  const set = (key: string, value: string) => onChange({ ...data, [key]: value });
  return <div className="space-y-4"><p className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)] p-4 text-sm text-[var(--color-slate)]">Homepage logos are managed on the main Partnerships page. The homepage automatically displays up to four strategic logos from there.</p><Field label="Heading" value={text(data, "heading")} onChange={(heading) => set("heading", heading)} /><Field label="Short introduction" value={text(data, "eyebrow")} onChange={(eyebrow) => set("eyebrow", eyebrow)} /><Area label="Description" value={text(data, "description")} onChange={(description) => set("description", description)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Button text" value={text(data, "button_label")} onChange={(button_label) => set("button_label", button_label)} /><Field label="Button link" value={text(data, "button_href")} onChange={(button_href) => set("button_href", button_href)} /></div></div>;
}
function GalleryFields({ data, onChange, canUpload }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void; canUpload: boolean }) {
  const items = Array.isArray(data.items) ? data.items.filter((item): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item)) : [];
  const set = (key: string, value: unknown) => onChange({ ...data, [key]: value });
  const update = (index: number, patch: Record<string, unknown>) => set("items", items.map((item, current) => current === index ? { ...item, ...patch } : item));
  const move = (index: number, step: number) => { const ordered = [...items]; [ordered[index], ordered[index + step]] = [ordered[index + step], ordered[index]]; set("items", ordered); };
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Gallery heading (optional)" value={text(data, "heading")} onChange={(heading) => set("heading", heading)} /><Area label="Short introduction (optional)" value={text(data, "description", "copy")} onChange={(description) => set("description", description)} /></div><p className="text-sm text-[var(--color-slate)]">Add one photo at a time. Choose or upload the image, add an optional label and caption, then use the arrows to set its display order.</p>{items.map((item, index) => { const metadata = item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? item.metadata as Record<string, unknown> : {}; return <details key={String(item.id || index)} open className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)]"><summary className="cursor-pointer px-4 py-3 font-semibold">{text(item, "title") || `Photo ${index + 1}`}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><MediaPicker label="Photo" value={text(item, "media_id")} fallback={text(item, "image_url")} canUpload={canUpload} onChange={(id, image_url) => update(index, { media_id: id, image_url })} /><Field label="Photo label (optional)" value={text(item, "title")} onChange={(title) => update(index, { title })} /><Area label="Caption (optional)" value={text(item, "description")} onChange={(description) => update(index, { description })} /><Field label="Image description (for accessibility)" value={text(metadata, "alt_text")} onChange={(alt_text) => update(index, { metadata: { ...metadata, alt_text } })} /><div className="flex flex-wrap gap-2"><button type="button" className={buttonClass} disabled={index === 0} onClick={() => move(index, -1)}>Move up</button><button type="button" className={buttonClass} disabled={index === items.length - 1} onClick={() => move(index, 1)}>Move down</button><button type="button" className="text-sm font-semibold text-red-700 underline" onClick={() => set("items", items.filter((_, current) => current !== index))}>Remove photo</button></div></div></details>; })}<button type="button" className={buttonClass} onClick={() => set("items", [...items, { id: crypto.randomUUID(), title: "", description: "", image_url: "", metadata: { alt_text: "" } }])}>+ Add photo</button></div>;
}
function PartnerFields({ items, onChange, canUpload, categorize }: { items: Record<string, unknown>[]; onChange: (items: Record<string, unknown>[]) => void; canUpload: boolean; categorize: boolean }) {
  const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, i) => i === index ? { ...item, ...patch } : item));
  const move = (index: number, step: number) => { const ordered = [...items]; [ordered[index], ordered[index + step]] = [ordered[index + step], ordered[index]]; onChange(ordered); };
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">{categorize ? "Add each partner logo and choose whether it is strategic or corporate. The Partners page displays the two groups separately." : "Add each partner logo. Logos appear together in the homepage carousel."}</p>
    {items.map((item, index) => <div key={String(item.id || index)} className="space-y-4 rounded-lg bg-[var(--color-paper)] p-4">
      <Field label="Partner name" value={text(item, "title")} onChange={(title) => update(index, { title })} />
      <Field label="Logo description (alt text)" value={text((item.metadata || {}) as Record<string, unknown>, "alt_text")} onChange={(alt_text) => update(index, { metadata: { ...(item.metadata as Record<string, unknown> || {}), alt_text } })} />
      {categorize && <label className="block text-sm font-semibold">Partner type<select className={inputClass} value={text((item.metadata || {}) as Record<string, unknown>, "partner_type") || "corporate"} onChange={(event) => update(index, { metadata: { ...(item.metadata as Record<string, unknown> || {}), partner_type: event.target.value } })}><option value="strategic">Strategic partner</option><option value="corporate">Corporate partner</option></select></label>}
      <MediaPicker label="Partner logo" value={text(item, "media_id")} fallback={text(item, "image_url")} canUpload={canUpload} onChange={(id, url) => update(index, { media_id: id, image_url: url })} />
      <Field label="Website link (optional, e.g. https://partner.org)" value={text(item, "href")} onChange={(href) => update(index, { href })} />
      <div className="flex flex-wrap gap-2"><button type="button" className={buttonClass} disabled={index === 0} onClick={() => move(index, -1)}>Move up</button><button type="button" className={buttonClass} disabled={index === items.length - 1} onClick={() => move(index, 1)}>Move down</button><button type="button" className={buttonClass} onClick={() => onChange(items.filter((_, i) => i !== index))}>Remove partner</button></div>
    </div>)}
    <button type="button" className={buttonClass} onClick={() => onChange([...items, { id: crypto.randomUUID(), title: "", image_url: "", href: "", ...(categorize ? { metadata: { partner_type: "corporate" } } : {}) }])}>+ Add partner logo</button>
  </div>;
}

function DocumentFields({ items, onChange, canUpload }: { items: Record<string, unknown>[]; onChange: (items: Record<string, unknown>[]) => void; canUpload: boolean }) {
  const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">Upload a PDF and a separate portrait cover image. Visitors will see the cover and be able to download the PDF from this page.</p>{items.map((item, index) => { const metadata = (item.metadata || {}) as Record<string, unknown>; return <details key={String(item.id || index)} open className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)]"><summary className="cursor-pointer px-4 py-3 font-semibold">{text(item, "title") || `Document ${index + 1}`}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><Field label="Document title" value={text(item, "title")} onChange={(title) => update(index, { title })} /><Area label="Description" value={text(item, "description")} onChange={(description) => update(index, { description })} /><Field label="Category (optional)" value={text(metadata, "category")} onChange={(category) => update(index, { metadata: { ...metadata, category } })} /><MediaPicker label="Portrait cover image" value={text(item, "cover_media_id")} fallback={text(item, "cover_image_url")} canUpload={canUpload} onChange={(id, cover_image_url) => update(index, { cover_media_id: id, cover_image_url })} /><MediaPicker label="PDF document" mediaKind="document" value={text(item, "media_id")} fallback={text(item, "href")} canUpload={canUpload} onChange={(id, href) => update(index, { media_id: id, href })} /><button type="button" className="text-sm text-red-700 underline" onClick={() => onChange(items.filter((_, current) => current !== index))}>Remove document</button></div></details>; })}<button type="button" className={buttonClass} onClick={() => onChange([...items, { id: crypto.randomUUID(), title: "", description: "", href: "", cover_image_url: "", metadata: { category: "" } }])}>+ Add PDF document</button></div>;
}

function TrainingCountdownFields({ data, onChange }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void }) {
  const set = (key: string, value: string) => onChange({ ...data, [key]: value });
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">Set the next public training programme below. The homepage shows the date, Ghana time and a live countdown. It automatically disappears once the time has passed.</p><Field label="Training title" value={text(data, "title")} onChange={(value) => set("title", value)} /><label className="block text-sm font-semibold">Start date and time (Ghana time)<input className={inputClass} type="datetime-local" value={text(data, "start_at")} onChange={(event) => set("start_at", event.target.value)} /></label><Area label="Short description (optional)" value={text(data, "description")} onChange={(value) => set("description", value)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Registration button text" value={text(data, "button_label") || "Register now"} onChange={(value) => set("button_label", value)} /><Field label="Registration link" value={text(data, "button_href")} onChange={(value) => set("button_href", value)} /></div></div>;
}

function VideoFields({ items, onChange }: { items: Record<string, unknown>[]; onChange: (items: Record<string, unknown>[]) => void }) {
  const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">Paste a YouTube watch, share, Shorts or live link. The public page creates the video thumbnail automatically—no image upload is needed.</p>{items.map((item, index) => { const metadata = item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? item.metadata as Record<string, unknown> : {}; return <details key={String(item.id || index)} open className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)]"><summary className="cursor-pointer px-4 py-3 font-semibold">{text(item, "title") || `Recording ${index + 1}`}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><Field label="Recording title" value={text(item, "title")} onChange={(title) => update(index, { title })} /><Area label="Short description (optional)" value={text(item, "description")} onChange={(description) => update(index, { description })} /><Field label="Recording date or label (optional)" value={text(metadata, "date")} onChange={(date) => update(index, { metadata: { ...metadata, date } })} /><Field label="YouTube link" value={text(item, "href")} onChange={(href) => update(index, { href })} /><button type="button" className="text-sm text-red-700 underline" onClick={() => onChange(items.filter((_, current) => current !== index))}>Remove recording</button></div></details>; })}<button type="button" className={buttonClass} onClick={() => onChange([...items, { id: crypto.randomUUID(), title: "", description: "", href: "", metadata: { date: "" } }])}>+ Add YouTube recording</button></div>;
}

function SeminarFields({ items, onChange, canUpload }: { items: Record<string, unknown>[]; onChange: (items: Record<string, unknown>[]) => void; canUpload: boolean }) {
  const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">Create each seminar card here. Add its flyer, topic, speaker, date and registration link in one place.</p>{items.map((item, index) => { const metadata = item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? item.metadata as Record<string, unknown> : {}; return <details key={String(item.id || index)} open className="rounded-lg border border-[var(--color-line)] bg-[var(--color-paper)]"><summary className="cursor-pointer px-4 py-3 font-semibold">{text(item, "title") || `Seminar ${index + 1}`}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><MediaPicker label="Seminar flyer" value={text(item, "media_id")} fallback={text(item, "image_url")} canUpload={canUpload} onChange={(id, image_url) => update(index, { media_id: id, image_url })} /><Field label="Seminar topic" value={text(item, "title")} onChange={(title) => update(index, { title })} /><Field label="Speaker" value={text(metadata, "speaker")} onChange={(speaker) => update(index, { metadata: { ...metadata, speaker } })} /><Field label="Date and time" value={text(metadata, "date")} onChange={(date) => update(index, { metadata: { ...metadata, date } })} /><Area label="Short description (optional)" value={text(item, "description")} onChange={(description) => update(index, { description })} /><Field label="Registration link" value={text(item, "href")} onChange={(href) => update(index, { href })} /><button type="button" className="text-sm text-red-700 underline" onClick={() => onChange(items.filter((_, current) => current !== index))}>Remove seminar</button></div></details>; })}<button type="button" className={buttonClass} onClick={() => onChange([...items, { id: crypto.randomUUID(), title: "", description: "", href: "", image_url: "", metadata: { speaker: "", date: "" } }])}>+ Add monthly seminar</button></div>;
}

function ExamAssessmentFields({ data, onChange }: { data: Record<string, unknown>; onChange: (data: Record<string, unknown>) => void }) {
  const questions = Array.isArray(data.questions) ? data.questions.filter((item): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item)) : [];
  const set = (key: string, value: unknown) => onChange({ ...data, [key]: value });
  const updateQuestion = (index: number, patch: Record<string, unknown>) => set("questions", questions.map((question, current) => current === index ? { ...question, ...patch } : question));
  const makeOption = () => ({ id: crypto.randomUUID(), text: "" });
  const makeQuestion = () => {
    const options = [makeOption(), makeOption(), makeOption(), makeOption()];
    return { id: crypto.randomUUID(), prompt: "", options, correct_option_id: options[0].id };
  };
  return <div className="space-y-5">
    <div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Practice assessment only.</strong> The access code and correct answers saved here are delivered to the visitor&apos;s browser so it can mark the result. Do not use this section for a secure or official examination.</div>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Assessment title" value={text(data, "heading") || "Corporate governance assessment"} onChange={(heading) => set("heading", heading)} /><Field label="Access code" value={text(data, "access_code") || "IoD-Gh-EXAM"} onChange={(access_code) => set("access_code", access_code)} /><Field label="Duration (minutes)" value={text(data, "duration_minutes") || "45"} onChange={(duration_minutes) => set("duration_minutes", duration_minutes)} /><Field label="Pass mark (%)" value={text(data, "pass_mark") || "70"} onChange={(pass_mark) => set("pass_mark", pass_mark)} /></div>
    <Area label="Candidate instructions" value={text(data, "instructions")} onChange={(instructions) => set("instructions", instructions)} />
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.show_answer_review !== false} onChange={(event) => set("show_answer_review", event.target.checked)} />Show the correct answers after submission</label>
    <div className="space-y-4 border-t border-[var(--color-line)] pt-5"><div><h3 className="font-semibold">Questions and answer key</h3><p className="mt-1 text-sm text-[var(--color-slate)]">Enter each answer option, then select the one that should be marked correct.</p></div>{questions.map((question, index) => {
      const options = Array.isArray(question.options) ? question.options.filter((item): item is Record<string, unknown> => !!item && typeof item === "object" && !Array.isArray(item)) : [];
      const correctId = text(question, "correct_option_id") || text(options[0] || {}, "id");
      const updateOption = (optionIndex: number, patch: Record<string, unknown>) => updateQuestion(index, { options: options.map((option, current) => current === optionIndex ? { ...option, ...patch } : option) });
      return <details key={text(question, "id") || index} open className="rounded-lg border border-[var(--color-line)] bg-white"><summary className="cursor-pointer px-4 py-3 font-semibold">Question {index + 1}{text(question, "prompt") ? `: ${text(question, "prompt")}` : ""}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><Area label="Question" value={text(question, "prompt")} onChange={(prompt) => updateQuestion(index, { prompt })} /><fieldset className="space-y-3"><legend className="text-sm font-semibold">Answer options</legend>{options.map((option, optionIndex) => <div className="flex items-center gap-3" key={text(option, "id") || optionIndex}><input type="radio" name={`correct-question-${text(question, "id") || index}`} checked={correctId === text(option, "id")} onChange={() => updateQuestion(index, { correct_option_id: text(option, "id") })} aria-label={`Mark answer ${optionIndex + 1} as correct`} /><div className="min-w-0 flex-1"><Field label={`Answer ${optionIndex + 1}`} value={text(option, "text")} onChange={(value) => updateOption(optionIndex, { text: value })} /></div>{options.length > 2 && <button type="button" className="text-sm text-red-700 underline" onClick={() => { const remaining = options.filter((_, current) => current !== optionIndex); updateQuestion(index, { options: remaining, correct_option_id: correctId === text(option, "id") ? text(remaining[0] || {}, "id") : correctId }); }}>Remove</button>}</div>)}</fieldset><div className="flex flex-wrap gap-3"><button type="button" className={buttonClass} disabled={options.length >= 6} onClick={() => updateQuestion(index, { options: [...options, makeOption()] })}>+ Add answer</button><button type="button" className="text-sm text-red-700 underline" onClick={() => set("questions", questions.filter((_, current) => current !== index))}>Remove question</button></div></div></details>;
    })}<button type="button" className={buttonClass} onClick={() => set("questions", [...questions, makeQuestion()])}>+ Add question</button></div>
  </div>;
}

function ProfileFields({ items, onChange, canUpload }: { items: Record<string, unknown>[]; onChange: (items: Record<string, unknown>[]) => void; canUpload: boolean }) {
  const update = (index: number, patch: Record<string, unknown>) => onChange(items.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <div className="space-y-4"><p className="text-sm text-[var(--color-slate)]">For Council, the matching key must exactly match the member name or role. For Secretariat, add each person&apos;s full public profile below.</p>{items.map((item, index) => { const metadata = (item.metadata || {}) as Record<string, unknown>; const displayName = text(metadata, "display_name") || text(item, "title") || `Profile ${index + 1}`; const role = text(metadata, "role"); const changeMetadata = (patch: Record<string, unknown>) => update(index, { metadata: { ...metadata, ...patch } }); return <details key={String(item.id || index)} className="rounded-lg border border-[var(--color-line)] bg-white"><summary className="cursor-pointer px-4 py-3 font-semibold">{displayName}{role && <span className="ml-2 text-sm font-normal text-[var(--color-slate)]">— {role}</span>}</summary><div className="space-y-4 border-t border-[var(--color-line)] p-4"><Field label="Matching key" value={text(item, "title")} onChange={(title) => update(index, { title })} /><Field label="Display name" value={text(metadata, "display_name")} onChange={(display_name) => changeMetadata({ display_name })} /><Field label="Role or department" value={role} onChange={(role) => changeMetadata({ role })} /><Area label="Short profile" value={text(metadata, "summary")} onChange={(summary) => changeMetadata({ summary })} /><Area label="Full biography" value={text(metadata, "biography")} onChange={(biography) => changeMetadata({ biography })} /><Field label="Photo description (alt text)" value={text(metadata, "alt_text")} onChange={(alt_text) => changeMetadata({ alt_text })} /><MediaPicker label="Profile photo" value={text(item, "media_id")} fallback={text(item, "image_url")} canUpload={canUpload} onChange={(id, url) => update(index, { media_id: id, image_url: url })} /><button type="button" className={buttonClass} onClick={() => onChange(items.filter((_, current) => current !== index))}>Remove profile</button></div></details>; })}<button type="button" className={buttonClass} onClick={() => onChange([...items, { id: crypto.randomUUID(), title: "", image_url: "", metadata: { alt_text: "", display_name: "", role: "", summary: "", biography: "" } }])}>+ Add profile</button></div>;
}
